version: "3"
services:
  rabbitMQ:
    image: rabbitmq:management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    volumes:
      - /data/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@rabbitmq
    ports:
      - "0.0.0.0:25672:25672"
      - "0.0.0.0:4369:4369"
      - "0.0.0.0:15671-15672:15671-15672"
      - "0.0.0.0:5671-5672:5671-5672"
    restart: always
